version: '3.7'

networks:
  backend:
    driver: bridge

services:
  db:
    networks:
      - backend
    image: postgres
    volumes:
      - ./docker/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    restart: always
    hostname: probes
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=probes_db,probes_db_test
      - POSTGRES_PASSWORD=password

  probes-application:
    networks:
      - backend
    build:
      context: .
    image: probes-application
    hostname: probes
    ports:
      - "8080:8080"
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/probes_db
